version: '3.8'

services:
  ft_onion:
    container_name: ft_onion
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-ft_onion:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sshd_config:/etc/ssh/sshd_config
      - ./torrc:/etc/tor/torrc
      - ./media:/usr/share/nginx/html/media

    networks:
      - ft_onion_network

networks:
  ft_onion_network:
    driver: bridge